common_args:
  training_type: "simulation"
  random_seed: 0
  excel_save_path: "D:\\"

data_args:
  dataset: "mnist"
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5
  experiment_niid_level: 0.5
  #experiment_niid_level = 1 means that the data is niid
  #experiment_niid_level = 0 means that the data is iid
  #experiment_niid_level = (0,1) e.g. 0.7 means that the data is partially niid

#  [Dataset + Model] :
#  mnist  cnn
#  femnist  cnn
#  fed_shakespeare  rnn
#  cifar10  cnn_web
#  fed_cifar100  resnet18_gn
#  svhn  cnn_web

model_args:
  model: "cnn"

train_args:
  federated_optimizer: "FedAB"
  client_id_list: "[]"
  client_num_in_total: 60
  client_num_per_round: 30
  comm_round: 250
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001

validation_args:
  frequency_of_the_test: 5

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"
  is_mobile: 0

tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_fedavg_mnist_lr